django-markitup has to be upgraded to work with Django 1.7 migrations
Otherwise you get this error on running migrations:

  django.db.utils.ProgrammingError: column "_summary_rendered" specified more than once

... which is due to this SQL being tried to create the core_organisation
table:

   CREATE TABLE "core_organisation" ("id" serial NOT NULL PRIMARY KEY, "created" timestamp with time zone NOT NULL, "updated" timestamp with time zone NOT NULL, "name" varchar(200) NOT NULL, "slug" varchar(200) NOT NULL UNIQUE, "summary" text NOT NULL, "started" varchar(10) NOT NULL, "ended" varchar(10) NOT NULL, "_summary_rendered" text NOT NULL, "_summary_rendered" text NOT NULL)