Add a dependency on the initial migration of the tasks application
This is to avoid the following error (traceback edited):

   > core:0037_migrate_data_for_parliamentary_sessions
  Error in migration: core:0037_migrate_data_for_parliamentary_sessions
  Traceback (most recent call last):
  [...]
    File "/home/travis/build/mysociety/pombola/pombola/core/migrations/0037_migrate_data_for_parliamentary_sessions.py", line 132, in forwards
      pk_2013_constituency.delete()
    File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/django/db/models/base.py", line 695, in delete
      collector.delete()
    File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/django/db/models/deletion.py", line 282, in delete
      sender=model, instance=obj, using=self.using
    File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
      response = receiver(signal=self, sender=sender, **named)
    File "/home/travis/build/mysociety/pombola/pombola/tasks/models.py", line 164, in delete_related_tasks
      Task.objects_for(instance).delete();
  [...]
  django.db.utils.ProgrammingError: relation "tasks_task" does not exist
  LINE 1: ...nt", "tasks_task"."log", "tasks_task"."note" FROM "tasks_tas...
                                                             ^