Vagrantfile: make sure a native JSON gem is installed
Otherwise you get this warning (which seems to cause a failing return code)
from collectstatic:

  pipeline.exceptions.CompilerError: [WARNING] MultiJson is using the
  default adapter (ok_json).We recommend loading a different JSON library
  to improve performance.