Ensure Django content-types are created before a complex migration
Something in this migration was causing the error:

  django.db.utils.IntegrityError: insert or update on table "auth_permission" violates foreign key constraint "content_type_id_refs_id_d043b34a"
  DETAIL:  Key (content_type_id)=(21) is not present in table "django_content_type".

... which seems like the same problem as this:

  https://groups.google.com/forum/#!topic/south-users/HeIhn-TzWVk

... i.e. the the content-types are created in response to the
post_syncdb signals sent by South, which are sent "quite late in the
process" so we call db.send_pending_create_signals() at the start of the
migration to make sure that they're present.