Fix a circular import bug when running South Africa tests in isolation
When running South Africa tests in isolation, this would fail with:

    File "/home/mark/pombola/pombola/pombola/south_africa/urls.py", line 4, in <module>
      from pombola.south_africa import views
  ImportError: cannot import name views

This was caused by a circular import caused by importing
PersonSpeakerMappingsMixin from pombola.south_africa.views instead of
pombola.core.views (where it's actually defined in any case).